
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")

        set_property(GLOBAL PROPERTY NS_CMAKE_PLATFORM_NAME "Linux")
		set_property(GLOBAL PROPERTY NS_CMAKE_PLATFORM_PREFIX "Linux")
		set_property(GLOBAL PROPERTY NS_CMAKE_PLATFORM_POSTFIX "Linux")

endif()
