
if(EMSCRIPTEN)

    set_property(GLOBAL PROPERTY NS_CMAKE_PLATFORM_NAME "Emscripten")
    set_property(GLOBAL PROPERTY NS_CMAKE_PLATFORM_PREFIX "Web")
    set_property(GLOBAL PROPERTY NS_CMAKE_PLATFORM_POSTFIX "Web")

endif()
